kotlin_release_version="1.2.30"
rules_kotlin_version = "67f4a6050584730ebae7f8a40435a209f8e0b48e"

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories(kotlin_release_version=kotlin_release_version)
kt_register_toolchains()


maven_server (
    name = "exposed_server",
    url = "https://dl.bintray.com/kotlin/exposed/",
)


maven_jar (
    name = "derby",
    artifact= "org.apache.derby:derby:10.14.1.0",
    sha1 = "3bcd8b1af3f8cd022d54d331e00064776be04f9c"
)

maven_jar (
    name = "exposed",
    artifact = "org.jetbrains.exposed:exposed:0.9.1",
    server = "exposed_server"
)